apiVersion: v1
kind: Pod
metadata:
  name: share-empty-dir
spec:
  containers:
  - name: container-1
    image: alpine
    command:
      - "bin/sh"
      - "-c"
      - "sleep 10000"
    volumeMounts:
      - name: shared-volume
        mountPath: /tmp/container-1
  - name: container-2
    image: alpine
    command:
      - "bin/sh"
      - "-c"
      - "sleep 10000"
    volumeMounts:
      - name: shared-volume
        mountPath: /tmp/container-2
  volumes:
  - name: shared-volume
    emptyDir: {}
