apiVersion: v1
kind: Pod
metadata:
  name: gce-volume-demo-pod
spec:
  containers:
  - name: host-path-demo-container
    image: alpine
    command:
      - "bin/sh"
      - "-c"
      - "sleep 10000"
    volumeMounts:
    - mountPath: /mount-host-path
      name: test-volume
  volumes:
  - name: test-volume
    gcePersistentDisk:
      pdName: gce-nfs-disk
      fsType: ext4
