apiVersion: v1
kind: Pod
metadata:
  name: host-path-demo-pod
spec:
  containers:
  - name: host-path-demo-container
    image: alpine
    command:
      - "bin/sh"
      - "-c"
      - "sleep 10000"
    volumeMounts:
    - mountPath: /mount-host-path
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /tmp/volume-data/node-host-path
