apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-with-config
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: config-vol
      mountPath: /etc/config
  volumes:
  - name: config-vol
    configMap:
      name: my-config
      items:
        - key: name
          path: configValue